app/models/blog.py
from app import db
from flask.ext.mongoengine.wtf import model_form

class BlogPost(db.Document):
    author = db.StringField(required=True, max_length=100)
    title = db.StringField(required=True, max_length=100)
    body = db.StringField(required=True)

BlogPostForm = model_form(BlogPost)

app/__init__.py
from flask import Flask
from flask.ext.mongoengine import MongoEngine

app = Flask(__name__)

app.config['DEBUG'] = True
app.config['MONGODB_SETTINGS'] = { 'db': 'blask' }
app.config['SECRET_KEY'] = 'SOMERANDOSTRING'

db = MongoEngine(app)

# Import and register the Blueprints
from app.routes.blog import blog
from app.routes.home import home
app.register_blueprint(blog)
app.register_blueprint(home)

# Because our routes are now spread across multiple modules, we need to use the Blueprint name to specify which module the desired route lives in. The string inside a call to url_for is blueprint_name.function_name. We can very easily update home.html to reflect this
# OLD: {{ url_for('home_page') }}
# NEW: {{ url_for('home.home_page') }}

app/routes/blog.py
from flask import Blueprint, render_template, redirect, url_for, request
#last 3 imports are for the new form
from app.models.blog import BlogPost, BlogPostForm

# Create the blog Blueprint.  Note that all routes on the blog blueprint have
# '/blog' prepended to them.
blog = Blueprint('blog', __name__, url_prefix='/blog')

@blog.route('/')  # Accessible at /blog/
def blog_page():
    """The blog page."""
    #objects() method comes from the Flask mongoengine
    posts = BlogPost.objects()
    return render_template('blog.html', posts=posts)

@blog.route('/new', methods=['GET', 'POST'])
def new():
    """Create a new post"""
    form = BlogPostForm(request.form)

    if request.method =='POST' and form.validate():
        form.save()
        return redirect(url_for('blog.blog_page'))

    return render_template('new.html', form =form)

@blog.route('/view/<id>')
# grab postObjectID parameter to have a static URL for people to bookmark.
def view(id):
    """View contents of a blog post"""
    # Retrive post comment using mongoEngine
    post = BlogPost.objects.get_or_404(id=id)
    return render_template('post.html', post=post)

app/routes/home.py
from flask import Blueprint, render_template

home = Blueprint('home', __name__)

@home.route('/')
def home_page():
    """The home page."""
    return render_template('home.html')

app/templates/blog.html
{% extends "home.html" %}
{% block title %}Blog | {{ super() }}{% endblock %}
<!-- super renders contents of parent title block -->
{% block current_page %}Blog{% endblock %}

{% block content %}
<h2>Check out my posts!</h2>

<ul class="posts">
    {% for post in posts %}
    {% set picture_id= range(1, 726)|random %}
        <li class="post">
         <a href="{{ url_for('blog.view', id=post.id) }}"><img class="post__img-thumb" src="https://unsplash.it/300/230/?image={{ picture_id }}"></a>
            <h3>{{ post.title }} <small>by {{ post.author }}</small></h3>
            <p>{{ post.body }}</p>
        </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/home.html
<html>

<head>
  <title>{% block title %}Blask!{% endblock %}</title>
  <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700,300,400'>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
  <nav>
    <div class="content">
      <h1><a href="/">Blask!</a></h1>
      <h2>{% block current_page %}Home{% endblock %}</h2>
      <ul class="menu">
        <li>
          <a href="{{ url_for('home.home_page') }}">Home</a>
        </li>
        <li>
          <a href="{{ url_for('blog.blog_page') }}">Blog</a>
        </li>
          <li>
          <a href="{{ url_for('blog.new') }}">Submit</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="content">
    {% block content %}
    <h2>Welcome to Blask!</h2> {% endblock %}
  </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>

</html>

app/templates/new.html
{% extends "home.html" %}
{% block title %}Blog | {{ super() }}{% endblock %}
{% block current_page %}Blog{% endblock %}

{% block content %}
    <h2>Create a New Post</h2>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.title.label }}
            {{ form.title }}
        </div>
        <div>
            {{ form.author.label }}
            {{ form.author }}
        </div>
        <div>
            {{ form.body.label }}
            {{ form.body }}
        </div>
        <input type="submit" value="Create">
    </form>
{% endblock %}

app/templates/post.html
{% extends "home.html" %}
{% block title %}Blog | {{ super() }} | post.title {% endblock %}
{% block current_page %}Blog{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <h2 class="post__author"> {{ post.author }}</h2>
    {% set picture_id= range(1, 726)|random %}
    <a href="{{ url_for('blog.view', id=post.id) }}"><img class="post__img-full" src="https://unsplash.it/600/400/?image={{ picture_id }}"></a>
    <p> {{ post.body }}</p>
    <a class="post__button" href="{{ url_for('blog.blog_page') }}">Back to Blogs</a>
{% endblock %}

templates/home.html
<html>

<head>
  <title>{% block title %}Blask!{% endblock %}</title>
  <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700,300,400'>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
  <nav>
    <div class="content">
      <h1><a href="/">Blask!</a></h1>
      <h2>{% block current_page %}Home{% endblock %}</h2>
      <ul class="menu">
        <li>
          <a href="{{ url_for('home_page') }}">Home</a>
        </li>
        <li>
          <a href="{{ url_for('blog_page') }}">Blog</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="content">
    {% block content %}
    <h2>Welcome to Blask!</h2> {% endblock %}
  </div>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>

</html>